default: &default
  adapter: sqlserver
  encoding: utf8
  username: khoi
  password: 123456
  host: localhost

development:
  <<: *default
  database: shopdouong

test:
  <<: *default
  database: RORsdouongs_test

production:
  <<: *default
  database: RORsdouongs_production
  username: RORsdouongs
  password: <%= ENV['RORSDOUONGS_DATABASE_PASSWORD'] %>