default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: mysql
  host: localhost

development:
  <<: *default
  database: shopdouong

test:
  <<: *default
  database: RORsdouongs_test

production:
  <<: *default
  database: RORsdouongs_production
  username: RORsdouongs
  password: <%= ENV['RORSDOUONGS_DATABASE_PASSWORD'] %>